# Generated by Django 3.2.6 on 2021-08-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesion_text',
            new_name='question_text',
        ),
    ]
